### PR TITLE
Remove port from req.headers.host when trying to match it

### PR DESCRIPTION
**Pull request by louy**

### CODE REVIEW

**Comment by benjie** [comment]
Interesting, what's the use case for this? Mehserve's intended to run on port 80 so this shouldn't be necessary for most users, but of course it actually binds to port `12439` (or `process.env.PORT`) by default - are you using it via this port?

:+1:

**Comment by louy** [comment]
Yep. And it stops detecting any services.

**Comment by benjie** [comment]
Would you be willing to sign the CLA? It's a standard doc from http://harmonyagreements.org/ and just requires your name and email.

http://www.clahub.com/agreements/timecounts/mehserve

**Comment by louy** [comment]
@benjie the CLA is quite complicated and I don't like signing documents I don't fully understand. Feel free to close this PR and fix the problem yourself (even with the exact same code).

**Comment by benjie** [comment]
Done, thanks @louy

**Pull request closed without merging**
